// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesGrades.Models;

namespace RazorPagesGrades.Migrations
{
    [DbContext(typeof(GradeDbContext))]
    [Migration("20191117223332_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorPagesGrades.Models.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SubjectAcronym")
                        .IsRequired();

                    b.Property<double>("Value");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("SubjectAcronym");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("RazorPagesGrades.Models.Subject", b =>
                {
                    b.Property<string>("Acronym")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3);

                    b.Property<string>("Name");

                    b.HasKey("Acronym");

                    b.ToTable("Subjects");

                    b.HasData(
                        new { Acronym = "MAT", Name = "Matematika" },
                        new { Acronym = "PRG", Name = "Programování" },
                        new { Acronym = "WEB", Name = "Webové aplikace" },
                        new { Acronym = "TEV", Name = "Tělocvik" },
                        new { Acronym = "CJL", Name = "Český jazyk a literatura" },
                        new { Acronym = "ANJ", Name = "Anglický jazyk" }
                    );
                });

            modelBuilder.Entity("RazorPagesGrades.Models.Grade", b =>
                {
                    b.HasOne("RazorPagesGrades.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectAcronym")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
